"use client";

import { useState, useRef } from "react";
import { Window, Button } from "@/components/win98-ui";
import { FileUp, Save, Check, X, AlertCircle, Info, ChevronRight, ChevronDown, Layout } from "lucide-react";
import { cn } from "@/lib/utils";
import Mermaid from "@/components/mermaid";

interface Finding {
    id: string;
    criticality: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    title: string;
    description: string;
    impact: string;
    files: string[];
    recommendation: string;
    valid?: boolean;
    rationale?: string;
}

interface StructuredReport {
    health: "POOR" | "FAIR" | "GOOD";
    summary: string;
    diagrams: {
        c1: string;
        c2: string;
        c3: string;
    };
    findings: Finding[];
}

export default function ReportPage() {
    const [report, setReport] = useState<StructuredReport | null>(null);
    const [validatedFindings, setValidatedFindings] = useState<Record<string, { valid: boolean, rationale: string }>>({});
    const [expandedFinding, setExpandedFinding] = useState<string | null>(null);
    const [activeTab, setActiveTab] = useState<"c1" | "c2" | "c3">("c1");
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = (event) => {
                try {
                    const json = JSON.parse(event.target?.result as string);
                    setReport(json);
                } catch (err) {
                    alert("Invalid JSON file");
                }
            };
            reader.readAsText(file);
        }
    };

    const handleValidation = (id: string, isValid: boolean) => {
        setValidatedFindings(prev => ({
            ...prev,
            [id]: { ...prev[id], valid: isValid }
        }));
    };

    const handleRationaleChange = (id: string, rationale: string) => {
        setValidatedFindings(prev => ({
            ...prev,
            [id]: { ...prev[id], rationale }
        }));
    };

    const handleExport = () => {
        if (!report) return;
        const finalReport = {
            ...report,
            findings: report.findings.map(f => ({
                ...f,
                ...validatedFindings[f.id]
            }))
        };
        const blob = new Blob([JSON.stringify(finalReport, null, 2)], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "validated_report.json";
        a.click();
    };

    if (!report) {
        return (
            <div className="max-w-2xl w-full">
                <Window title="Load Agent Report" icon={<FileUp className="w-4 h-4" />}>
                    <div className="text-center space-y-6 py-8">
                        <div className="flex justify-center">
                            <div className="win98-inset bg-win-white p-8 rounded-full">
                                <FileUp className="w-12 h-12 text-win-blue" />
                            </div>
                        </div>
                        <div className="space-y-2">
                            <h2 className="text-xl font-bold">Import report.json</h2>
                            <p className="text-sm text-win-dark-gray">Select the structured JSON output generated by the agent.</p>
                        </div>
                        <Button onClick={() => fileInputRef.current?.click()}>
                            CHOOSE FILE
                        </Button>
                        <input
                            type="file"
                            ref={fileInputRef}
                            className="hidden"
                            accept=".json"
                            onChange={handleFileUpload}
                        />
                    </div>
                </Window>
            </div>
        );
    }

    return (
        <div className="max-w-6xl w-full grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Sidebar: Summary & Health */}
            <div className="lg:col-span-1 space-y-6">
                <Window title="System Health" icon={<Info className="w-4 h-4" />}>
                    <div className={cn(
                        "p-4 text-center font-bold text-2xl win98-inset mb-4",
                        report.health === "POOR" ? "bg-red-500 text-white" :
                            report.health === "FAIR" ? "bg-yellow-400 text-black" : "bg-green-500 text-white"
                    )}>
                        {report.health}
                    </div>
                    <div className="bg-win-white p-3 win98-inset text-sm h-48 overflow-auto">
                        <p>{report.summary}</p>
                    </div>
                </Window>

                {report.diagrams && (report.diagrams.c1 || report.diagrams.c2 || report.diagrams.c3) && (
                    <Window title="C4 Model Diagrams" icon={<Layout className="w-4 h-4" />}>
                        <div className="flex gap-1 mb-4">
                            {(["c1", "c2", "c3"] as const).map((tab) => (
                                <Button
                                    key={tab}
                                    className={cn("flex-1 text-xs", activeTab === tab ? "bg-win-blue text-white" : "")}
                                    onClick={() => setActiveTab(tab)}
                                >
                                    {tab.toUpperCase()}
                                </Button>
                            ))}
                        </div>
                        <div className="min-h-[300px]">
                            {report.diagrams[activeTab] ? (
                                <Mermaid chart={report.diagrams[activeTab]} />
                            ) : (
                                <div className="flex items-center justify-center h-[300px] win98-inset bg-gray-100 text-xs italic">
                                    No {activeTab.toUpperCase()} diagram found.
                                </div>
                            )}
                        </div>
                    </Window>
                )}

                <Window title="Actions" icon={<Save className="w-4 h-4" />}>
                    <div className="space-y-4">
                        <div className="text-xs text-win-dark-gray italic">
                            Validated: {Object.keys(validatedFindings).length} / {report.findings.length}
                        </div>
                        <Button className="w-full bg-blue-100" onClick={handleExport}>
                            EXPORT VALIDATED REPORT
                        </Button>
                        <Button className="w-full" onClick={() => setReport(null)}>
                            LOAD DIFFERENT FILE
                        </Button>
                    </div>
                </Window>
            </div>

            {/* Main: Findings List */}
            <div className="lg:col-span-2 space-y-4">
                <h2 className="text-xl font-bold text-white drop-shadow-md flex items-center gap-2">
                    <AlertCircle className="w-5 h-5" />
                    Detected Findings
                </h2>

                {report.findings.map((finding) => (
                    <Window
                        key={finding.id}
                        title={`${finding.criticality}: ${finding.title}`}
                        className={cn(
                            "transition-all",
                            expandedFinding === finding.id ? "ring-2 ring-win-blue" : ""
                        )}
                    >
                        <div className="space-y-4">
                            <div className="flex justify-between items-start">
                                <div className="space-y-1">
                                    <p className="text-sm font-bold underline">Impact:</p>
                                    <p className="text-sm">{finding.impact}</p>
                                </div>
                                <Button
                                    onClick={() => setExpandedFinding(expandedFinding === finding.id ? null : finding.id)}
                                    className="p-0 w-6 h-6 flex items-center justify-center"
                                >
                                    {expandedFinding === finding.id ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                                </Button>
                            </div>

                            {expandedFinding === finding.id && (
                                <div className="space-y-4 pt-4 border-t border-win-dark-gray">
                                    <div className="space-y-1">
                                        <p className="text-sm font-bold underline">Description:</p>
                                        <p className="text-sm whitespace-pre-wrap">{finding.description}</p>
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-sm font-bold underline">Recommendation:</p>
                                        <p className="text-sm italic">{finding.recommendation}</p>
                                    </div>
                                    <div className="space-y-1">
                                        <p className="text-sm font-bold underline">Affected Files:</p>
                                        <ul className="text-xs font-mono bg-black text-green-400 p-2 win98-inset max-h-24 overflow-auto">
                                            {finding.files.map(f => <li key={f}>{f}</li>)}
                                        </ul>
                                    </div>
                                </div>
                            )}

                            <div className="pt-4 border-t border-win-dark-gray flex flex-col md:flex-row gap-4 items-end">
                                <div className="flex-1 space-y-1 w-full">
                                    <p className="text-xs font-bold">Validation Rationale:</p>
                                    <textarea
                                        className="w-full p-2 h-16 text-sm win98-inset bg-win-white outline-none"
                                        placeholder="Enter why this finding is valid or invalid..."
                                        value={validatedFindings[finding.id]?.rationale || ""}
                                        onChange={(e) => handleRationaleChange(finding.id, e.target.value)}
                                    />
                                </div>
                                <div className="flex gap-2">
                                    <Button
                                        className={cn(
                                            "flex items-center gap-1",
                                            validatedFindings[finding.id]?.valid === true ? "bg-green-200 outline outline-2 outline-green-600" : ""
                                        )}
                                        onClick={() => handleValidation(finding.id, true)}
                                    >
                                        <Check className="w-4 h-4" />
                                        VALID
                                    </Button>
                                    <Button
                                        className={cn(
                                            "flex items-center gap-1",
                                            validatedFindings[finding.id]?.valid === false ? "bg-red-200 outline outline-2 outline-red-600" : ""
                                        )}
                                        onClick={() => handleValidation(finding.id, false)}
                                    >
                                        <X className="w-4 h-4" />
                                        INVALID
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </Window>
                ))}
            </div>
        </div>
    );
}
